# Generated by Django 5.1.7 on 2025-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
